import ROOT
import correctionlib

year=20240
correctionlib.register_pyroot_binding()
ROOT.gInterpreter.Declare('#include "mysf.h"')
print("eval_{0}".format(year))
if(year==20220):
    ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20220);')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoBCD", (char*)"sf", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoBCD", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoBCD", (char*)"sfdown", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoBCD", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoBCD", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoBCD", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2022Re-recoBCD", (char*)"sf", (char*)"Medium", 1.1, 30.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
elif(year==20221):
    ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20221);')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoE+PromptFG", (char*)"sf", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoE+PromptFG", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2022Re-recoE+PromptFG", (char*)"sfdown", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoE+PromptFG", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoE+PromptFG", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2022Re-recoE+PromptFG", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2022Re-recoE+PromptFG", (char*)"sf", (char*)"Medium", 1.1, 30.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2022EE", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
elif(year==20230):
    ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20230);')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptC", (char*)"sf", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptC", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptC", (char*)"sfdown", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronMVASF((char*)"2023PromptC", (char*)"sf", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptC", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptC", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptC", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2023PromptC", (char*)"sf", (char*)"Medium", 1.1, 30.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
elif(year==20231):
    ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20231);')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptD", (char*)"sf", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptD", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2023PromptD", (char*)"sfdown", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptD", (char*)"sf", (char*)"RecoBelow20", 1.1, 19.999,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptD", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2023PromptD", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2023PromptD", (char*)"sf", (char*)"Medium", 1.1, 30.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
elif(year==20240):
    ROOT.gInterpreter.ProcessLine('auto corr = MyCorrections(20240);')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2024Prompt", (char*)"sf", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2024Prompt", (char*)"sfup", (char*)"wp80iso", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronIDSF ((char*)"2024Prompt", (char*)"sfdown", (char*)"Medium", 1.1, 34.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2024Prompt", (char*)"sf", (char*)"Reco20to75", 1.1, 20.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_electronTRKSF((char*)"2024Prompt", (char*)"sf", (char*)"RecoAbove75", 1.1, 75.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_photonSF((char*)"2024Prompt", (char*)"sf", (char*)"Medium", 1.1, 30.0,0.3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"pt", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"nom", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_dn", 100, 1.5, 45)')
    ROOT.gInterpreter.ProcessLine('corr.eval_met_corr((char*)"phi", (char*)"PuppiMET", (char*)"2023BPix", (char*)"MC",(char*)"pu_up", 100, 1.5, 45)')
print("eval_el_EtDependent_scale_smeaer")
ROOT.gInterpreter.ProcessLine('corr.eval_electronEtDependentScale((char*)"scale", 357900, 0.5, 0.99, 40, 1.0)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronEtDependentSmearing((char*)"smear", 40, 0.99, 0.5)')
ROOT.gInterpreter.ProcessLine('corr.eval_electronEtDependentSmearing((char*)"esmear", 40, 0.99, 0.5)')
print("eval_muon_med")
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 35, 35,(char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 35,    (char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 35,    (char*)"stat")')
print("eval_muon_high")
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"nominal")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"syst")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonTRKSF((double)0.9, 350, 350,(char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonIDSF ((double)0.9, 350,     (char*)"stat")')
ROOT.gInterpreter.ProcessLine('corr.eval_muonISOSF((double)0.9, 350,     (char*)"stat")')
print("eval_btv")
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"L",1.1,350.0,4)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"L",1.1,350.0,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"central",(char*)"L",1.1,350.0,0)')
print("eval_up")
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"up",(char*)"L",1.1,35.0,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"up_statistic",(char*)"L",1.1,35.0,5)')
print("eval_down")
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"down",(char*)"L",1.1,35.0,5)')
ROOT.gInterpreter.ProcessLine('corr.eval_btvSF((char*)"down_statistic",(char*)"L",1.1,35.0,5)')
print("eval_tau")
ROOT.gInterpreter.ProcessLine('corr.eval_tauJETSF(65.2,11,5,"Tight","Tight","nom")')
print("eval_jetCORR")
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 2)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 3)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 4)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 5)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 6)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 7)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 8)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30, 9)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,10)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,11)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,12)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,13)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,14)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,15)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,16)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,17)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,18)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,19)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,20)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,21)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,22)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,23)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,24)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,25)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,26)')
ROOT.gInterpreter.ProcessLine('corr.eval_jesUnc(1.5,30,27)')
print("eval_jetCORR_others")
#ROOT.gInterpreter.ProcessLine('corr.eval_jetCORR(0.5,1.,2.,150,15,380000,3)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerScaleFactor(1.5,30, 0)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerScaleFactor(1.5,30,+1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerScaleFactor(1.5,30,-1)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerPtResolution(2.5,20,30)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerPtResolution(3.0,20,30)')
ROOT.gInterpreter.ProcessLine('corr.eval_jerPtResolution(3.5,20,30)')
if(year==20230):
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-2.2,2)')
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(6.5,-2.2,2)')
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-6.2,2)')
elif(year==20231):
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-2.2,3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(6.5,-2.2,3)')
    ROOT.gInterpreter.ProcessLine('corr.eval_jetVetoMap(2.5,-6.2,3)')
print("eval_jetSel")
ROOT.gInterpreter.ProcessLine('corr.eval_jetSel(0,-0.2,0.4,0.25,0.1,0.15,0.1,1,2)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetSel(1,-0.2,0.4,0.25,0.1,0.15,0.1,1,2)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetSel(0,-4.2,0.4,0.25,0.1,0.15,0.1,0,2)')
ROOT.gInterpreter.ProcessLine('corr.eval_jetSel(1,-4.2,0.4,0.25,0.1,0.15,0.1,0,2)')
print("eval_muon_scale")
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_scale(1, 30.0, 0.5, 2.5, -1)')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_scale(0, 30.0, 0.5, 2.5, -1)')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_resol(30.5, 0.5, 13)')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_scale_var(30.6, 0.5, 2.5, -1, "up")')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_scale_var(30.6, 0.5, 2.5, -1, "dn")')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_resol_var(30.5, 30.6, 0.5, "up")')
ROOT.gInterpreter.ProcessLine('corr.eval_muon_pt_resol_var(30.5, 30.6, 0.5, "dn")')
