
def plotCategory(key):
    plotCategoryDict = dict()
    plotCategoryDict.update({"kPlotData"      :[ 0]})
    plotCategoryDict.update({"kPlotqqWW"      :[ 1]})
    plotCategoryDict.update({"kPlotggWW"      :[ 2]})
    plotCategoryDict.update({"kPlotTT"        :[ 3]})
    plotCategoryDict.update({"kPlotTW"        :[ 4]})
    plotCategoryDict.update({"kPlotDY"        :[ 5]})
    plotCategoryDict.update({"kPlotEWKSSWW"   :[ 6]})
    plotCategoryDict.update({"kPlotQCDSSWW"   :[ 7]})
    plotCategoryDict.update({"kPlotEWKWZ"     :[ 8]})
    plotCategoryDict.update({"kPlotWZ"        :[ 9]})
    plotCategoryDict.update({"kPlotZZ"        :[10]})
    plotCategoryDict.update({"kPlotNonPrompt" :[11]})
    plotCategoryDict.update({"kPlotVVV"       :[12]})
    plotCategoryDict.update({"kPlotTVX"       :[13]})
    plotCategoryDict.update({"kPlotVG"        :[14]})
    plotCategoryDict.update({"kPlotHiggs"     :[15]})
    plotCategoryDict.update({"kPlotWS"        :[16]})
    plotCategoryDict.update({"kPlotOther"     :[17]})
    plotCategoryDict.update({"kPlotEM"        :[18]})
    plotCategoryDict.update({"kPlotBSM"       :[19]})
    plotCategoryDict.update({"kPlotSignal0"   :[20]})
    plotCategoryDict.update({"kPlotSignal1"   :[21]})
    plotCategoryDict.update({"kPlotSignal2"   :[22]})
    plotCategoryDict.update({"kPlotSignal3"   :[23]})
    plotCategoryDict.update({"kPlotSignal4"   :[24]})
    plotCategoryDict.update({"kPlotSignal5"   :[25]})
    plotCategoryDict.update({"kPlotCategories":[26]})

    try:
        return plotCategoryDict[key][0]
    except Exception as e:
        print("Wrong key({0}): {1}".format(key,e))
